-- Write a query to display employee name , job of all employees who are 
-- working as manager and works at CHICAGO.
-- List the employees who have commission greater than the maximum salary of all the SALESMAN
-- who don't report to KING directly.
-- Display the names of employees from department number 10 with salary greater than that
-- of all employees working in other departments.